### ISSUE TITLE
AttributeError: 'module' object has no attribute 'packages'

### ISSUE THREAD

**Issue by housemusic42** [1aN0rmus/TekDefense-Automater#25]
Getting this error after trying run the latest code push from the git repo

```bash
yo@supfoo ~/other/TekDefense-Automater $ python Automater.py 4.4.4.4
Traceback (most recent call last):
  File "Automater.py", line 40, in <module>
    from siteinfo import SiteFacade, Site
  File "/home/yo/other/TekDefense-Automater/siteinfo.py", line 40, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'
yo@supfoo ~/other/TekDefense-Automater $
```

**Comment by mixedup4x4** [comment]
I put the new Automater files in their own folder to temporarily get around that issue.

**Comment by housemusic42** [comment]
arg... i updated my urllib3 and requests and we're back in business. PEBKAC!

thanks for a great tool!
