### ISSUE TITLE
Error in packages

### ISSUE THREAD

**Issue by seifreed** [1aN0rmus/TekDefense-Automater#28]
Running Ubuntu 14.10

Trace

Traceback (most recent call last):
  File "Automater.py", line 40, in <module>
    from siteinfo import SiteFacade, Site
  File "/home/seifreed/tools/malware/TekDefense-Automater/siteinfo.py", line 39, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'

**Comment by p4r4n0y1ng** [comment]
seifreed,
  Can you please tell me what version of the requests module you have loaded. If I am insulting you here, I apologize, but for brevity I will put it here. Open a python interactive session, then import requests, then utilize the __version__ attribute:

python
Python 2.7.10 (blah blah blah) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__version__
'2.9.1'

Tell me what that bottom line says please.

**Comment by seifreed** [comment]
Hi,

How are you buddy?

Thanks for the reply!

Look at this..

sudo pip install requests -U
Downloading/unpacking requests from
https://pypi.python.org/packages/2.7/r/requests/requests-2.9.1-py2.py3-none-any.whl#md5=58a444aaa02780ad01983f5f540e67b2
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Installing collected packages: requests
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by
OS
Successfully installed requests
Cleaning up...

seifreed@linux-analyzer:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'version'
>>>

WTF!

--
Marc Rivero López | @seifreed | www.ecrime.info

2016-01-27 23:04 GMT+01:00 p4r4n0y1ng <notifications@github.com>:

**Comment by p4r4n0y1ng** [comment]
Oh man!!!! my bust. First of all that stinking install process is WEIRD. I especially love the
"Installing collected packages: requests Found existing installation: requests 2.2.1 Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS Successfully installed requests"

UMMM......WHAT?

Anyway, here's where I steered you wrong. Please use __version__ (double underscores each side). Not "version".

should look like:

requests.__version__

Thanks for the patience and apologies again

**Comment by p4r4n0y1ng** [comment]
It is screwing it up here because of the markdown support in the editor. Please use:

requests."underscore""underscore"version"underscore""underscore"

and obviously replace "underscore""underscore" with 2 underscores on each side.

after we're done fixing this - I'll go learn markdown nastiness too ;)

**Comment by mixedup4x4** [comment]
I've created a pull request that is a requirements.txt file

**Comment by p4r4n0y1ng** [comment]
Great idea - Marc, did the update to your requests module help as I think it did? I want to make sure before we close this issue out.

**Comment by einarf** [comment]
Just a side note here that might be useful. Messing with the default python packages in the OS is normally not what you want.

Better options :
* `pip install --user requests` puts the package in `$HOME/.local/lib/` instead.
* Use a virtualenv

Then you don't have to deal with "Not uninstalling blah at /usr/lib/python2.7/dist-packages, owned by
OS" and you can even upgrade pip version (pip on ubuntu 14.10 is ancient).
