### ISSUE TITLE
ImportError: No module named outputs

### ISSUE THREAD

**Issue by acquiredsecurity** [1aN0rmus/TekDefense-Automater#41]
Hi. I'm new here and to linux I am having a bit of trouble getting Automater set up. I've done my best to search around but can't find an answer to my issue. This is the error I receive when trying to run Automater:

Traceback (most recent call last):
  File "/usr/local/bin/Automater.py", line 40, in <module>
    from siteinfo import SiteFacade, Site
  File "/usr/local/bin/siteinfo.py", line 35, in <module>
    from outputs import SiteDetailOutput
ImportError: No module named outputs

Any help would be greatly appreciated.

Thanks!

**Comment by KDPryor** [comment]
The outputs.py module comes with the full package. You need to have it in
the folder with automater.py when you run it.

Hope that helps.
Ken
