### ISSUE TITLE
AttributeError - urllib3 issue

### ISSUE THREAD

**Issue by cyberlive-GREM** [1aN0rmus/TekDefense-Automater#42]
Hello - 

Trying to work through the same issue that was reported and closed back in November 24, 2015.    Original post from user is below : 

python Automater.py 4.4.4.4
Traceback (most recent call last):
  File "Automater.py", line 40, in <module>
    from siteinfo import SiteFacade, Site
  File "/home/yo/other/TekDefense-Automater/siteinfo.py", line 40, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'

This user updated urllib3 and requests.  I have this exact same issue on fresh installs of Ubuntu 14.0.4 and 16.0.4.  I did troubleshooting through python, etc...  

The install method i followed was from this site.

Thanks for any help...

**Comment by groda** [comment]
Hi I was able to reproduce your error by downgrading the requests library to Version 1.2.0:
`$ pip install --upgrade  requests==1.2.0`
and I get the error when running Automater:
>    requests.packages.urllib3.disable_warnings()
> AttributeError: 'module' object has no attribute 'disable_warnings'

**Solution**: install the latest version of requests (2.18.4) like this:
`$ pip install --upgrade  requests`
